package co.edu.udes.backend.enums;

public enum ErrorCode {
    STUDENT_NOT_FOUND("Estudiante no encontrado"),
    TEACHER_NOT_FOUND("Profesor no encontrado"),
    SUBJECT_NOT_FOUND("Asignatura no encontrada"),
    GROUP_NOT_FOUND("Grupo no encontrado"),
    GROUP_ALREADY_EXISTS("Ya existe un grupo con este nombre para esta materia"),
    ALREADY_ENROLLED("Ya estás inscrito en esta materia"),
    PREREQUISITE_NOT_FOUND("No tienes registro del prerrequisito"),
    PREREQUISITE_NOT_APPROVED("No has aprobado el prerrequisito"),
    CAREER_NOT_FOUND("Carrera no encontrada"),
    CAREER_ALREADY_EXISTS("La carrera ya existe."),
    SUBJECT_ALREADY_EXISTS("La materia ya existe."),
    SEMESTER_NOT_FOUND("Semestre no encontrado"),
    SEMESTER_HAS_SUBJECTS("El semestre contiene materias"),
    SEMESTER_ALREADY_EXISTS("El semestre ya existe"),
    INVALID_PREREQUISITE_SEMESTER("Prerequisite invalido, o materia en mismo semestre"),
    STUDENT_ALREADY_EXISTS("El estudiante ya existe."),
    STUDENT_NOT_ENROLLED_IN_CAREER("El estudiante no se encuentra matriculado en la carrera."),
    SUBJECT_NOT_IN_CAREER("La materia no se encuentra en la carrera"),
    GROUP_FULL("El grupo esta lleno."),
    STUDENT_ALREADY_ENROLLED("El estudiante ya se encuentra matriculado."),
    SCHEDULE_NOT_FOUND("Horario no encontrado"),
    SUBJECT_ALREADY_ASSIGNED("La materia ya esta asignada a un semestre."),
    PREREQUISITE_NOT_COMPLETED("No ha cursado la materia de pre-requisito"),
    NO_ENROLLED_GROUPS("No hay grupos matriculados."),
    TEACHER_ALREADY_EXISTS("El profesor ya existe"),
    GROUP_WITHOUT_SCHEDULE("El grupo no tiene horarios asignados."),
    TEACHER_WORKLOAD_EXCEEDED("La carga horaria del profesor esta en su limite."),
    GROUP_ALREADY_ASSIGNED_TO_ANOTHER_TEACHER("El grupo ya está asignado a otro profesor."),
    TEACHER_SCHEDULE_CONFLICT("El profesor tiene asignada una clase durante, o a la misma hora."),
    GROUP_SCHEDULE_CONFLICT("El grupo ya tiene un horario asignado a la misma hora, o durante esa hora."),
    STUDENT_NOT_ENROLLED("El estudiante no esta matriculado en ese grupo."),
    NOT_CREATED_EVALUATION("La evaluacion no pudo ser creada."),
    CHAT_NOT_FOUND("Chat no Encontrado"),
    STUDENT_NOT_IN_CHAT("Estudiante no esta en este chat"),
    INVALID_MESSAGE_TARGET("Debe seleccionar un destino valido para el mensaje"),
    FORUM_NOT_FOUND("Foro no encontrado"),
    STUDENT_NOT_IN_FORUM_GROUP("Estudiante no esta en el grupo"),
    NOTIFICATION_NOT_FOUND(" Notificacion no encontrada"),
    TEACHER_NOT_ASSIGNED_TO_GROUP("Profesor no asignado al grupo"),
    INVALID_PERIOD_DATES("Fecha de periodos invalidas."),
    PERIOD_NOT_FOUND("Periodo no encontrado"),
    SEMESTER_DATES_REQUIRED("Las fechas son requeridas."),
    PERIOD_ALREADY_EXISTS("El periodo no existe"),
    PERIODS_ALREADY_INITIALIZED("Los periodos ya fueron iniciados."),
    ATTENDANCE_NOT_FOUND("Asistencia no encontrada"),
    ATTENDANCE_ALREADY_EXISTS("La asistencia ya exsite"),
    INVALID_CLASS_DATE("Fecha de clase invalida."),
    STUDENT_NOT_IN_GROUP("El estudiante no se encuentra en el grupo."),
    NO_CLASSES_IN_PERIOD("La clase no esta en el periodo (corte)"),
    EMPTY_STUDENT_LIST("Lista de estudiantes vacia."),
    PERIOD_DATES_MISSING("Fechas de periodo vacia."),
    INVALID_PERIOD_CONFIGURATION("Configuracion de periodo invalida."),
    INVALID_PERIOD_WEIGHTS("Porcentaje de periodos invalidos."),
    MISSING_PERIOD_DATES("No hay fechas de periodos."),
    ROLE_NOT_FOUND("Rol no encontrado"),
    INVALID_ROLE("Rol invalido"),
    INVALID_CREDENTIALS("Contraseña o email invalidos."),
    NOT_FOUND_MATERIAL("No existe material con ese ID"),
    CODE_IS_NULL("El código de material no puede ser nulo o vacío "),
    MATERIAL_EXISTS("Ya existe el material"),
    CODE_CONVERTD_IN_NULL("El código de material se convirtió a nulo"),
    CODE_IS_SAME("El código nuevo no puede ser igual al código actual"),
    PLACE_NOT_FOUND("No se encontro el lugar"),
    PLACE_NAME("Ya existe un espacio con ese nombre"),
    PLACE_EXISTS("El sitio no existe"),
    RESERVE_NOT_FOUND("La reserva no fue encontrada"),
    RESERVECODE_EXISTS("El codigo de la reserva ya existe"),
    DATE_OF_RESERVE("La fecha de la reserva no puede ser nula."),
    RESERVE_EXISTS("Ya existe una reserva para ese lugar, hora y fecha."),
    MAINTENANCE_NOT_EXISTS("No existe ese mantenimiento"),
    LOAN_EXISTS("Ya existe un préstamo con ese código"),
    LOAN_NOT_FOUND("#EL PRESTAMO NO EXISTE"),
    LOAN_CODE_IS_NULL("El código de préstamo no puede ser nulo o vacío"),
    LOAN_CODE_IS_SAME("El código nuevo no puede ser igual al código actual"),
    USER_NOT_FOUND("El usuario no existe"),
    NO_PERIODS_FOUND("Periodos no encontrados"),
    INVALID_PERIOD_COUNT("Cuenta de periodo invalida"),
    NO_GRADES_FOUND_FOR_SUBJECT("No hay notas para esa materia"),
    INCOMPLETE_PERIODS_FOR_SUBJECT("Periodos incompletos.");

    private final String message;

    ErrorCode(String message) {
        this.message = message;
    }

    public String getMessage() {
        return message;
    }
}